# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comm.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncomm.proto\"\x07\n\x05\x45mpty\")\n\x04\x44\x61ta\x12\n\n\x02id\x18\x01 \x01(\t\x12\x15\n\x05model\x18\x02 \x01(\x0b\x32\x06.Model\"\x1d\n\x02ID\x12\x0b\n\x03num\x18\x01 \x01(\x05\x12\n\n\x02id\x18\x02 \x01(\t\"\x17\n\x05Model\x12\x0e\n\x06\x62uffer\x18\x01 \x01(\x0c\x32L\n\x13\x43ommunicationServer\x12\x18\n\x08GetModel\x12\x03.ID\x1a\x05.Data\"\x00\x12\x1b\n\x08SendData\x12\x05.Data\x1a\x06.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'comm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=14
  _globals['_EMPTY']._serialized_end=21
  _globals['_DATA']._serialized_start=23
  _globals['_DATA']._serialized_end=64
  _globals['_ID']._serialized_start=66
  _globals['_ID']._serialized_end=95
  _globals['_MODEL']._serialized_start=97
  _globals['_MODEL']._serialized_end=120
  _globals['_COMMUNICATIONSERVER']._serialized_start=122
  _globals['_COMMUNICATIONSERVER']._serialized_end=198
# @@protoc_insertion_point(module_scope)
